CREATE DATABASE ejer1

CREATE TABLE PERSONAS(
CI			INTEGER			NOT NULL,
NOMBRE		VARCHAR(20)		NOT NULL,
APELLIDO	VARCHAR(20)		NOT NULL,
CALLE		VARCHAR(20),
NUMERO		INTEGER,
ESQUINA		VARCHAR(20),
EMAIL		VARCHAR(30),
PRIMARY KEY(CI));

SELECT * FROM PERSONAS



CREATE TABLE CLIENTES(
CI_CLI	INTEGER		NOT NULL,
NUMERO	INTEGER		NOT NULL,

PRIMARY KEY (CI_CLI));


CREATE TABLE CAMION(
POTENCIA	INTEGER			NOT NULL,
MATRICULA	VARCHAR(20)		NOT NULL,
MODELO		VARCHAR(20)		NOT NULL,
TIPO		VARCHAR(20)		NOT NULL,


PRIMARY KEY (MATRICULA));

SELECT * FROM CAMION

ALTER TABLE PERSONAS ADD FECHANACIMIENTO	VARCHAR(10)		NOT NULL;

SELECT * FROM PERSONAS

ALTER TABLE PERSONAS ALTER COLUMN APELLIDO VARCHAR (15);

PERSONAS

ALTER TABLE PERSONAS ALTER COLUMN NOMBRE VARCHAR (30);

DROP TABLE CAMION

CREATE TABLE CUENTA (

NUMERO_CUENTA	VARCHAR(20)	NOT NULL,
NOMBRE_SUCURSAL	VARCHAR(20)	NOT NULL,
SALDO			INTEGER		NOT NULL,

PRIMARY KEY (NUMERO_CUENTA));

INSERT INTO CUENTA
VALUES ('C-9732', 'NARANJO', 1200)

INSERT INTO CUENTA (NOMBRE_SUCURSAL, SALDO, NUMERO_CUENTA) VALUES ('NARANJO', 1200, 'C-9734')

SELECT * FROM CUENTA

CREATE TABLE PRESTAMOS (

NUMERO_PRESTAMO	VARCHAR(20)	NOT NULL,
NOMBRE_SUCURSAL	VARCHAR(20)	NOT NULL,
SALDO			INTEGER		NOT NULL,

PRIMARY KEY (NUMERO_PRESTAMO)); 

INSERT INTO PRESTAMOS
VALUES ('C-2021', 'NARANJO', 300)
INSERT INTO PRESTAMOS
VALUES ('C-2022', 'NARANJO', 400)

SELECT * FROM CUENTA
SELECT * FROM PRESTAMOS

INSERT INTO CUENTA
SELECT NUMERO_PRESTAMO,NOMBRE_SUCURSAL,  200
FROM PRESTAMOS
WHERE NOMBRE_SUCURSAL = 'NARANJO'

DELETE FROM PRESTAMOS

DELETE FROM CUENTA 
WHERE NUMERO_CUENTA = 'C-9733'

UPDATE CUENTA 
SET SALDO = SALDO *1.05, NOMBRE_SUCURSAL = 'MIXCO'
WHERE SALDO >=1000

SELECT SALDO
UPDATE C
SET C.SALDO = SALDO*2
FROM CUENTA AS C 
WHERE NOMBRE_SUCURSAL = 'MIXCO' 

